### ISSUE TITLE
Please add a binary

### ISSUE THREAD

**Issue by eugenesvk** [kdl-org/kdl-rs#106]
For easier testing of (in)valid docs (there is a playground, but it's web-based and only supports v2), js/py packages require runtimes, so a nice contained single file would be helpful

The binary would take a file and spit out all parsing errors if any
```
Error:
  × Expected valid value.
   ╭────
 1 │ foo 1.
   ·     ─┬
   ·      ╰── invalid float
   ╰────
  help: Floating point numbers must be base 10, and have numbers after the decimal point.
```

**Comment by zkat** [comment]
I mean there’s already kdl-fmt and kdlfmt (heh), both of which seem to be fairly thin cli wrappers around this implementation, but also providing stuff like editorconfig support, which is nice. Is using one of those insufficient? They do things like syntax and stuff too.

**Comment by eugenesvk** [comment]
Oh, I didn't know about them, then I guess it's more of a documentation issue in the main repo

https://github.com/dj95/kdl-fmt doesn't have a binary

https://github.com/hougesen/kdlfmt does, but the latest is flagged as a virus on Windows :)
