### ISSUE TITLE
Fails to parse if children are on same line

### ISSUE THREAD

**Issue by porglezomp** [kdl-org/kdl-rs#11]
The following fails to parse:
```rust
node { child }
```
I don't think the spec specifies whether or not this should parse, but I would like it to. Looking at the code of the nodejs implementation, I *think* that one will parse this?

**Comment by zkat** [comment]
I seem to have completely failed to write an explicit section for children blocks, but the intention is definitely that you MUST have a newline there.

**Comment by porglezomp** [comment]
My use-case is something like this, trying to accommodate for the fact that I want *some* structured properties. This might just be a case that KDL isn't as convenient for, though.
```
materials {
    material "floor" "Lambert" { albedo 0.5 0.5 0.8 }
}
```

Would this mean that `node {; child }` would be allowed?

**Comment by zkat** [comment]
oh wait! I misspoke!

This is definitely a spec compliance bug. Yes, you can and should be able to do exactly what you're asking for, but the Rust parser currently doesn't support it.

See:
```
nodes := linespace* (node nodes?)? linespace*

node := ('/-' ws*)? identifier (node-space node-props-and-args)* (node-space* node-children ws*)? node-terminator
node-props-and-args := ('/-' ws*)? (prop | value)
node-children := ('/-' ws*)? '{' nodes '}'
node-space := ws* escline ws* | ws+
node-terminator := single-line-comment | newline | ';' | eof
```

**Comment by zkat** [comment]
new parser addresses this.
