### ISSUE TITLE
Enhancement: Disable the nom bitvec feature

### ISSUE THREAD

**Issue by porglezomp** [kdl-org/kdl-rs#12]
nom supports doing bit-level parsing. However, if you're not using that, you can disable the feature and save on a few dependencies.

I only noticed this because of https://github.com/bitvecto-rs/bitvec/issues/105 causing a compilation failure (that I was able to work around) but it would be nice to not have unused dependencies regardless.

**Comment by jam1garner** [comment]
Took a bit of a dive into this. Might be impossible at the time being?

nom's features:
![image](https://user-images.githubusercontent.com/8260240/117047965-745f8180-ace0-11eb-8adf-8a5a85e1effd.png)

We need `alloc` for `many0`/`many1`,`many_till`, however enabling the `alloc` feature in `nom` will also activate (as per the above screenshot) `bitvec/alloc` whichhhhhhh will implicitly activate `bitvec`.

I believe the relevant issue is Geal/nom#1232 which depends on rust-lang/cargo#8832 to resolve without hacky options.

One (not great) possibility for resolution is copying the implementations for `many{0,1}` and `many_till` into `kdl` itself, then use none of the features of `nom`. I don't think this will be that hard to accomplish so I'll submit a PR with that approach real quick and then it can be determined if that is an acceptable solution for losing 6-11 unneeded dependencies.
