### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by tiffany352** [kdl-org/kdl-rs#20]
The [README.md](https://github.com/kdl-org/kdl-rs/blob/a358750d898dd125456bd9937335bffb03d2edb8/README.md), the [description on crates.io](https://crates.io/crates/kdl) and the [description on docs.rs](https://docs.rs/kdl/3.0.0/kdl/), mention that this project is under the Parity license with a broken link to the old license file.

It looks like the project is Apache2 now according to https://github.com/kdl-org/kdl-rs/commit/0dbf75c78eb918b6966aae27fb1d7591791f15de, so those should probably be updated.

**Comment by zkat** [comment]
Oh strange. I wonder what happened. I thought I updated all of those. I'll see if there's some unpushed changes once I'm back home

**Comment by zkat** [comment]
For the record: the license should be Apache-2.0 as of 2.0.0.

**Comment by zkat** [comment]
This is resolved, I think,
