### ISSUE TITLE
Spec says "arguments", kdl-rs says "values"

### ISSUE THREAD

**Issue by enterprisey** [kdl-org/kdl-rs#24]
It looks like what the spec calls "Arguments", kdl-rs calls "values" (see the field names for the KdlNode struct). Should something be done?

**Comment by zkat** [comment]
yeaaaah. That's an unfortunate inconsistency. I've been (slowly) working on a new parser for kdl-rs that will hopefully correct a lot of this stuff, tho

**Comment by zkat** [comment]
I think this is addressed in the upcoming version.
