### ISSUE TITLE
Unquoted strings cause hard to reason about KDL error

### ISSUE THREAD

**Issue by KallDrexx** [kdl-org/kdl-rs#27]
My first time playing with KDL and I have the following test KDL:

```rust
        let content = "
settings {
    first second
    num 12345
    string \"abcdefg\"
}";
```

When parsing this I get the following KDL error:

```
KdlError { input: "\nsettings {\n    first second\n    num 12345\n    string \"abcdefg\"\n}", offset: 1, line: 1, column: 1, kind: Other }
```

It was not clear to me that unquoted strings are not allowed in the KDL spec.  However, this error had me stumped for over an hour because it claimed the whole document was wrong for an unknown reason.  Quoting the `second` and the `12345` made this pass validation.  

While I don't really agree with unquoted strings not being allowed (but that's a spec issue not kdl-rs issue), kdl-rs should at least pinpoint to the right word that's causing the error, and should have a better error kind for this situation, such as `InvalidValueType`.

**Comment by zkat** [comment]
New version will address this.
