### ISSUE TITLE
Expose `identifier`, `node_value`, etc. functions?

### ISSUE THREAD

**Issue by jihchi** [kdl-org/kdl-rs#28]
I've built [a tool](https://github.com/jihchi/kq) which is heavily relying on kdl-rs, specifically some internal/private functions, for example:
1. [identifier](https://github.com/kdl-org/kdl-rs/blob/v3.0.0/src/parser.rs#L148-L151)
1. [whitespace](https://github.com/kdl-org/kdl-rs/blob/v3.0.0/src/parser.rs#L437-L448)
1. [node_value](https://github.com/kdl-org/kdl-rs/blob/v3.0.0/src/parser.rs#L180-L190)

I have [copied](https://github.com/jihchi/kq/blob/1.0.6/src/kdlrs.rs) relevant code from kdl-rs repository because those are private at the moment.

It would be wonderful if I can access those functions directly from kdl crate instead of copy-paste.

**Comment by zkat** [comment]
Thinking about this, I don't think it's a good idea to expose parser internals from the upcoming kdl version, as I'd like to have more flexibility around what those APIs look like without every change being a breaking change.

You're free to continue copy-pasting things as needed, of course, as long as you attribute the code appropriately per the Apache license.

THAT SAID.

I think you don't _need_ access to these internals with the new API, which supports parsing of identifiers/entries/nodes/documents individually and is able to preserve (and give programmatic access to) whitespace/comments/etc.

If there's any specific needs beyond that that kdl-rs could have APIs for, I'm happy to explore that within the bounds of the document-oriented API, though! As such, I'm going to close this particular issue, but thanks for the contribution, and I'm excited to see where kq goes 🤩
