### ISSUE TITLE
Odd error span with invalid float

### ISSUE THREAD

**Issue by CAD97** [kdl-org/kdl-rs#52]
```rust
fn main() {
    let test = r#"
// Nodes can be separated into multiple lines
title \
    "Some title"


// Files must be utf8 encoded!
smile "😁"

// Instead of anonymous nodes, nodes and properties can be wrapped
// in "" for arbitrary node names.
"!@#$@$%Q#$%~@!40" "1.2.3" "!!!!!"=true

// The following is a legal bare identifier:
foo123~!@#$%^&*.:'|?+ "weeee"

// And you can also use unicode!
ノード　お名前="☜(ﾟヮﾟ☜)"

// kdl specifically allows properties and values to be
// interspersed with each other, much like CLI commands.
foo bar=true "baz" quux=false 1 2 3.
"#;

    let err: kdl::KdlError = test.parse::<kdl::KdlDocument>().unwrap_err();
    println!("{:?}", miette::Report::from(err));
}
```

```
  × Expected valid value.
    ╭─[21:1]
 21 │ // interspersed with each other, much like CLI commands.
 22 │ foo bar=true "baz" quux=false 1 2 3.
    ·        ─┬
    ·         ╰── invalid float
    ╰────
  help: Floating point numbers must be base 10, and have numbers after the decimal point.
```

**Comment by CAD97** [comment]
According to my twitter feed, you should be using [nom-locate](https://lib.rs/crates/nom_locate) and [nom-supreme](https://lib.rs/crates/nom-supreme) to build nom parsers which capture good error reporting information.

**Comment by zkat** [comment]
I have no idea what's even going on here. Some help would be super welcome.

**Comment by CAD97** [comment]
Honestly I don't either.

**Comment by to-json** [comment]
Are y'all still able to reproduce? My guess had to do with SourceSpan being a (codepoint|character|byte)wise offset, which would be a Miette thing, but, I actually get the right span (560) when I run it (MacOS Ventura)

**Comment by zkat** [comment]
This is a bug in the old parser, and is irrelevant in the new parser, which has been written from scratch. Please re-file if you run into it in the new one, too.
