### ISSUE TITLE
Insertion/removal behavior

### ISSUE THREAD

**Issue by jaxter184** [kdl-org/kdl-rs#62]
The insertion/removal behavior in the following cases seem a bit unintuitive to me:
* Inserting/removing the positional argument at the last index in a list of entries
* Removing the positional argument when there are keyword arguments interleaved with them

Based on the doc comments for `KdlNode::remove` and `KdlNode::insert`, these both seem like bugs. If someone could confirm that is the case, I'll go ahead and PR my fork: https://github.com/kdl-org/kdl-rs/compare/main...jaxter184:kdl-rs:main

Also, a tangentially related sidenote, but `KdlNode::remove` will remove only the first instance in the case of multiple keywords, which is potentially inconsistent with the `KdlNode::get` behavior of returning the last instance. Maybe it would make sense to remove every instance of a keyword and return only the last instance?

**Comment by jaxter184** [comment]
Looking through it again, it seems like many of the functions have extra checks for `current_idx > idx` that don't seem necessary as far as I can tell, and that's part of why the insert/remove of the last index was having trouble, so I've removed those checks, and the tests seem to still pass. The last commit in my fork reflects this change.

**Comment by zkat** [comment]
ooooh. Good catch! Please do send a PR, that looks good :)
