### ISSUE TITLE
kdl 1 updated to a recent miette release?

### ISSUE THREAD

**Issue by cbiffle** [kdl-org/kdl-rs#84]
Hi! It's possible you don't want to mess with this during the kdl2 runup, but for programs still using kdl1, I notice that the crate is on miette 5.10. More recent versions of miette look like they have useful API improvements. I wonder if it would be possible to get a kdl1 release with an updated miette before kdl2 lands? (It would need to happen in that order because both would, I assume, be breaking changes.)

**Comment by zkat** [comment]
done :)

4.7.0 now depends on `miette@7.4.0`
