### ISSUE TITLE
Use tabs (U+0009) for autoformatting indentation

### ISSUE THREAD

**Issue by toastal** [kdl-org/kdl-rs#85]
The tab character is a more user-friendly & accessible option for indentation since users can configure the width for whatever their preference desires or impairment requires. Printing becomes simpler for indentation depth (where 1 `\t` = 1 level of indentation). As a bonus, the output size is smaller not filled with more separating spaces than is required.

According to the spec <https://github.com/kdl-org/kdl/blob/main/SPEC.md#whitespace>, `U+0009` is considered “non-[Newline](https://github.com/kdl-org/kdl/blob/main/SPEC.md#newline) [white space](https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt)” & is allowable.

At a minimum, it would be nice to to see tabs supported as an option, but this would make indention a more complicated input ADT of `enum Indent { Tab, Space(u8) }` to support tabs & configurable space depth.

See more arguments (be warned there is a lot of bike-shedding, however many legitimate concerns): https://github.com/prettier/prettier/issues/7475

**Comment by zkat** [comment]
I'd be happy to take a patch that exposes `(KdlDocument|KdlNode)::autoformat_config(&mut self, config: &FormatConfig)` and replaces the internal `autoformat_impl`s with it. `FormatConfig` can then look something like this:

```rust
pub struct FormatConfig {
  indent_level: usize,
  indent_char: char,
  no_comments: bool,
}
```

How does that sound?

**Comment by Tamschi** [comment]
> How does that sound?

`#[non_exhaustive]` and `Default`, right?

(I'd prefer if tabs were the default in general too, but that seems like a breaking-change kind of thing.
To me it's more important that the non-`_config` call matches what one with `&FormatConfig::default()` does.)

**Comment by Tamschi** [comment]
I'll give it a go. Are you okay with pulling in Bon as builder generator?

**Comment by zkat** [comment]
@Tamschi go for it. It.. shouldn't affect build times much, right? idk how heavy it is as far as proc macros go.
