### ISSUE TITLE
4.7.0 is a breaking minor release because it changes the miette major version

### ISSUE THREAD

**Issue by cbiffle** [kdl-org/kdl-rs#97]
I use this crate and miette in the new version of the Hubris build tools, and I've been tracking down some build breakage this morning. It turns out to be due to accepting the kdl 4.6->4.7 minor update, which switched the major version of miette that kdl's errors use to 7.

Miette 7.4 errors do not implement Miette 5.x's diagnostic trait, so if the code using kdl is also using miette 5.x you get errors like this:

```
error[E0277]: the trait bound `KdlError: miette::Diagnostic` is not satisfied
   --> /home/cbiffle/.cargo/git/checkouts/exhubris-9c333d7376aea40c/969a8fb/tools/build/src/appcfg.rs:212:23
    |
212 |         Ok(src.parse()?)
    |                       ^ the trait `miette::Diagnostic` is not implemented for `KdlError`, which is required by `Result<_, ErrReport>: FromResidual<Result<Infallible, _>>`
    |
    = help: the following other types implement trait `miette::Diagnostic`:
              InstallError
              MietteDiagnostic
              MietteError
    = note: required for `ErrReport` to implement `From<KdlError>`
    = note: required for `Result<KdlDocument, ErrReport>` to implement `FromResidual<Result<Infallible, KdlError>>`

error[E0277]: the trait bound `SourceSpan: From<miette::protocol::SourceSpan>` is not satisfied
   --> /home/cbiffle/.cargo/git/checkouts/exhubris-9c333d7376aea40c/969a8fb/tools/build/src/appcfg.rs:239:41
    |
239 |                 labels=[LabeledSpan::at(*first.name().span(), "expected 'app' here")],
    |                         --------------- ^^^^^^^^^^^^^^^^^^^^ the trait `From<miette::protocol::SourceSpan>` is not implemented for `SourceSpan`, which is required by `miette::protocol::SourceSpan: Into<SourceSpan>`
    |                         |
    |                         required by a bound introduced by this call
```

Keep in mind that Cargo assumes an update from 4.6 to 4.7 can be done safely without user intervention, since the package is effectively declaring the new API to be a strict superset of the old (due to semver). This is not true between kdl 4.6 and 4.7.

Since this crate's use of miette is exposed at the API boundary, this crate's miette major version is effectively a committed part of the API. While I'm excited about getting access to recent versions of miette, this may need to happen outside the 4.x series.

**Comment by zkat** [comment]
This should be fixed and released now. Sorry for the trouble.
